### ISSUE TITLE
BatchEditorRenderData could not be found

### ISSUE THREAD

**Issue by brettcook99** [Dreaming381/Latios-Framework#28]
I'm trying to get Latios up and running on 2022.2.9f1 and I'm getting 4 errors about 'BatchEditorRenderData' could not be found.  Searching the Unity docs doesn't yield anything pertaining to that.  What am I missing?

**Comment by Dreaming381** [comment]
The Latios Framework is not compatible with pre44 or pre 47 yet due to this bug:
https://forum.unity.com/threads/pre-47-closed-subscenes-wont-load-with-zero-errors.1406512/

I do have a compatible version locally. If you want it, let me know. But I cannot guarantee it will work as well as Pre15 with 2022.2.0.

**Comment by teoAlivanoglou** [comment]
> 

Hello, I'd love the compatible version

**Comment by Dreaming381** [comment]
Closed as 0.7 is released and is compatible with Entities [1.0.10].
