### ISSUE TITLE
This modification means i can use entities 1.0.0-per.44?

### ISSUE THREAD

**Issue by jiangjiatao** [Dreaming381/Latios-Framework#30]
![image](https://user-images.githubusercontent.com/18566483/227417308-b9f00580-2f72-4c79-9a26-6811023a9339.png)

**Comment by Dreaming381** [comment]
No. The official 0.6.6 release is not compatible with anything newer than Pre.15. See #28 if you want something that kinda works with Pre.47 which is just a hotfix of Pre.44. Nothing works with Pre.44 due to the bug that was fixed in Pre.47.

I am investigating options for future compatibility for 0.7.x releases.

**Comment by Dreaming381** [comment]
Closed as 0.7 is released and is compatible with the latest Entities [1.0.10].
