### ISSUE TITLE
Can I specify Latios-Framework to use ENABLE_TRANSFORM_V1 instead of globally using ENABLE_TRANSFORM_V1, because some of my plugins may be using the V2 version?

### ISSUE THREAD

**Issue by oshellhahaha** [Dreaming381/Latios-Framework#31]

**Comment by Dreaming381** [comment]
This is not possible because it is the Transforms Package itself that needs this define. Also, 0.6.X is no longer officially supported as it fundamentally is incompatible with the newer ECS package releases.

I recommend using 0.7 (it is in beta in the prerelease branch). It provides a much more modern QVVS Transform system, and has scripting define toggles to change the transform system used. One of these modes is a compatibility mode for Unity Transforms, although few things are implemented for that mode currently. This is an area I am hoping the community will help implement, as it isn't a personal use case of mine and so I don't have a good sense of what the best implementation decisions should be. You can read more about it here: https://forum.unity.com/threads/0-7-0-beta-latios-framework-for-ecs-megathread.797685/page-5#post-9016213

I hope that helps!

**Comment by Dreaming381** [comment]
Closed as 0.7 is released.
